language: minimal

services:
  - docker

install: 
  - echo minor > versionType.txt
  - echo Test > destination.txt
  - docker build . --tag="nwisweb_tableau_dockerinstance"
  - docker run --name nwisweb_data_connector_docker nwisweb_tableau_dockerinstance
  - cat ./coverage/lcov.info | coveralls
