const states = {
  Alabama: "AL",
  Alaska: "AK",
  "American Samoa": "AS",
  Arizona: "AZ",
  Arkansas: "AR",
  California: "CA",
  Colorado: "CO",
  Connecticut: "CT",
  Delaware: "DE",
  "District of Columbia": "DC",
  "Federated States Of Micronesia": "FM",
  Florida: "FL",
  Georgia: "GA",
  Guam: "GU",
  Hawaii: "HI",
  Idaho: "ID",
  Illinois: "IL",
  Indiana: "IN",
  Iowa: "IA",
  Kansas: "KS",
  Kentucky: "KY",
  Louisiana: "LA",
  Maine: "ME",
  "Marshall Islands": "MH",
  Maryland: "MD",
  Massachusetts: "MA",
  Michigan: "MI",
  Minnesota: "MN",
  Mississippi: "MS",
  Missouri: "MO",
  Montana: "MT",
  Nebraska: "NE",
  Nevada: "NV",
  "New Hampshire": "NH",
  "New Jersey": "NJ",
  "New Mexico": "NM",
  "New York": "NY",
  "North Carolina": "NC",
  "North Dakota": "ND",
  "Northern Mariana Islands": "MP",
  Ohio: "OH",
  Oklahoma: "OK",
  Oregon: "OR",
  Palau: "PW",
  Pennsylvania: "PA",
  "Puerto Rico": "PR",
  "Rhode Island": "RI",
  "South Carolina": "SC",
  "South Dakota": "SD",
  Tennessee: "TN",
  Texas: "TX",
  Utah: "UT",
  Vermont: "VT",
  "Virgin Islands": "VI",
  Virginia: "VA",
  Washington: "WA",
  "West Virginia": "WV",
  Wisconsin: "WI",
  Wyoming: "WY"
};

const siteTypes = {
  Glacier: "GL",
  Ocean: "OC",
  Coastal: "OC-CO",
  Estuary: "ES",
  Lake: "LK",
  Stream: "ST",
  Canal: "ST-CA",
  Ditch: "ST-DCH",
  "Tidal stream": "ST-TS",
  Spring: "SP",
  Well: "GW",
  "Collector or Ranney type well": "GW-CR",
  "Extensometer well": "GW-EX",
  "Hyporheic-zone well": "GW-HZ",
  "Interconnected wells": "GW-IW",
  "Multiple wells": "GW-MW",
  "Test hole": "GW-TH",
  "Other subsurface": "SB",
  Cave: "SB-CV",
  "Groundwater drain": "SB-GWD",
  "Tunnel, shaft, or mine": "SB-TSM",
  "Unsaturated zone": "SB-UZ",
  Wetland: "WE",
  Land: "LA",
  Excavation: "LA-EX",
  Outcrop: "LA-OU",
  Sinkhole: "LA-SNK",
  "Soil hole": "LA-SH",
  Shore: "LA-SR",
  Facility: "FA",
  Cistern: "FA-CI",
  "Combined sewer": "FA-CS",
  Diversion: "FA-DV",
  "Field, Orchard, or Nursery": "FA-FON",
  "Golf course": "FA-GC",
  "Hydroelectric plant": "FA-HP",
  "Laboratory or sample-prep area": "FA-QC",
  Landfill: "FA-LF",
  Outfall: "FA-OF",
  Pavement: "FA-PV",
  "Septic system": "FA-SPS",
  "Storm sewer": "FA-STS",
  "Thermoelectric plant": "FA-TEP",
  "Waste-injection well": "FA-WIW",
  "Wastewater sewer": "FA-SEW",
  "Wastewater disposal": "FA-WWD",
  "Wastewater-treatment plant": "FA-WWTP",
  "Water-distribution system": "FA-WDS",
  "Water-supply treatment plant": "FA-WTP",
  "Water-use establishment": "FA-WU",
  "Aggregate water-use establishment": "AW",
  "Aggregate ground-water use": "AG",
  "Aggregate surface-water-use": "AS"
};

export { states, siteTypes };
